[book]
authors = [{{ authors }}]
language = "en"
multilingual = false
src = "book"
title = "{{ project-name }} Documentation"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
cname = "GITHUB_PAGES_URL"
curly-quotes = true
edit-url-template = "https://github.com/{{ repository_path }}/{{ project-name }}/edit/main/{path}"
git-repository-url = "https://github.com/{{ repository_path }}/{{ project-name }}"
preferred-dark-theme = "navy"
