[values]
include_code_of_conduct = true
include_precommit = true
include_security_policy = true
license = "MIT"
repository_path = "owner/name"
# optional
architecture_url = "XXX"

## codecov
include_codecov = true
# optional
codecov_graph_token = "XXX"

## mdbook
include_mdbook = true
# optional
mdbook_pages_url = "XXX"
