name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: basic-tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Expand template
        uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: >-
            --define include_mdbook="true"
            --define mdbook_pages_url="XXX"
            --define include_precommit="true"
            --define codecov="XXX"
            --define architecture_url="XXX"
            --define repository_path="XXX"
      - name: Build setup
        uses: ./.github/actions/build_setup
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          # TODO: add more test / do CI steps?
          cargo check
