name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lychee_links:
    name: Broken URL checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          fail: true
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: typos
      uses: crate-ci/typos@master
  conventional_commits:
    name: Conventional commit checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: cocogitto check
        uses: oknozor/cocogitto-action@v3
  expand_template:
    name: Expand template
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: basic-tests
      CARGO_GENERATE_VALUE_CI: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Expand template
        uses: cargo-generate/cargo-generate-action@latest
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: >-
            --define=include_mdbook=true
            --define=mdbook_pages_url=XXX
            --define=include_precommit=true
            --define=codecov=XXX
            --define=architecture_url=XXX
            --define=repository_path=XXX
      - name: Build setup
        uses: ./.github/actions/build_setup
      - run: |
          mv $PROJECT_NAME ${{ runner.temp }}/
          cd ${{ runner.temp }}/$PROJECT_NAME
          # TODO: add more test / do CI steps?
          cargo check
